### ISSUE TITLE
delaunay-triangulation

### ISSUE THREAD

**Issue by 18020126185** [sibozhang/Depth-Guided-Inpainting#1]
In file included from /home/tt/Depth-Guided-Inpainting/catkin_ws/src/loam_velodyne/src/VideoInpaintingTexSynth.cpp:1:0:
/home/tt/Depth-Guided-Inpainting/catkin_ws/src/loam_velodyne/src/utils.hpp:16:10: fatal error: delaunay-triangulation/vector2.h: no such file or directory
 #include "delaunay-triangulation/vector2.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

delaunay-triangulation is a empty directory, but some header file needed in VideoInpainting.cpp.

**Comment by michaelzhang-ai** [comment]
You need to install ros kinetic
